FROM rust:1.95.0 as builder

WORKDIR /app

COPY . .

RUN cargo build --release

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/target/release/backend ./backend
EXPOSE 3000
CMD ["./backend"]